### ISSUE TITLE
Unable to uninstall module

### ISSUE THREAD

**Issue by unional** [unional/jspm-p4#2]
Install is working, but uninstall fails:

`jspm uninstall my:module`:

```
warn Dependency my:module is not an existing primary install.

ok Uninstall complete.
```

Files in `jspm_packages` are not removed, and `package.json` and `config.js` are not updated.

@guybedford, do you have any idea? I can't find anything on the doc (https://github.com/jspm/jspm-cli/blob/master/docs/registry-api.md) on how to handle uninstall properly.

**Comment by guybedford** [comment]
This is a duplicate of https://github.com/jspm/jspm-cli/issues/1271.

**Comment by unional** [comment]
Fixed in latest build of jspm. Not jspm-p4 related.
